# Generated by Django 3.2.16 on 2023-01-02 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bday',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='profile',
            name='orientation',
            field=models.TextField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='showme',
            field=models.TextField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.TextField(blank=True, max_length=25),
        ),
    ]
