# Generated by Django 3.2.16 on 2023-01-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230102_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bday',
            field=models.DateField(default='{{user_profile.bday}}'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='orientation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='showme',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
